@extends('frontend.layout.master')
@section('title', 'Komek | E-Commerce')
@include('frontend.widgets.topbar')
@include('frontend.widgets.navbar')
@section('content')
@include('frontend.widgets.featured')
@include('frontend.widgets.categories')
@include('frontend.widgets.offer')
    @include('frontend.widgets.products')
    @include('frontend.widgets.subscribe')
    @include('frontend.widgets.products2')
    @include('frontend.widgets.vendor')
@endsection
